services:
  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

  spring-app:
    image: "${DOCKER_HUB_USERNAME}/sukbakji-server:${DEPLOY_ENV}"
    container_name: "spring-app"
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_LOCATION: /app/resources/application.yml
    volumes:
      - ./src/main/resources/application.yml:/app/resources/application.yml
    depends_on:
      - redis
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge