services:
  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  spring-blue:
    image: "${DOCKER_HUB_USERNAME}/sukbakji-server:blue"
    container_name: "spring-blue"
    ports:
      - "8080:8080"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    depends_on:
      - redis
    networks:
      - backend
    restart: always

  spring-green:
    image: "${DOCKER_HUB_USERNAME}/sukbakji-server:green"
    container_name: "spring-green"
    ports:
      - "8081:8080"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    depends_on:
      - redis
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge