services:
  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

  spring-app:
    build: .
    container_name: "spring-app"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge