name: Deploy to Staging and Production

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_ENV: ${{ steps.set_env.outputs.DEPLOY_ENV }}
    env:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.yml from GitHub Secrets
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Create Apple Auth Key from GitHub Secrets
        env:
          APPLE_AUTH_KEY_P8: ${{ secrets.APPLE_AUTH_KEY_P8 }}
          APPLE_AUTH_KEY_NAME: ${{ secrets.APPLE_AUTH_KEY_NAME }}
        run: |
          echo "$APPLE_AUTH_KEY_P8" | base64 --decode | tr -d '\r' > ./src/main/resources/$APPLE_AUTH_KEY_NAME

      - name: Create Firebase Admin SDK JSON from GitHub Secrets
        env:
          FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
        run: |
          mkdir -p ./src/main/resources/firebase
          echo "$FIREBASE_ADMINSDK_JSON" | base64 --decode | tr -d '\r' > ./src/main/resources/firebase/firebase-adminsdk.json

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Set up Redis with password
        run: |
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine Deployment Environment
        id: set_env
        run: |
          if [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "DEPLOY_ENV=staging" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=latest" >> $GITHUB_ENV
            echo "DEPLOY_ENV=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sukbakji-server:${{ env.DEPLOY_ENV }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sukbakji-server:${{ env.DEPLOY_ENV }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: ${{ needs.build.outputs.DEPLOY_ENV }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      APPLE_AUTH_KEY_NAME: ${{ secrets.APPLE_AUTH_KEY_NAME }}
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          s